### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by Sija** [luckyframework/lucky#1022] opened 2020-03-03 23:03 UTC
Lucky claims to be _extremely fast_ but in https://github.com/the-benchmarker/web-frameworks it's at spot no. 97, way below js, php, ruby... so, what's the situation here?

**Comment by paulcsmith** [comment] 2020-03-03 23:06
I need to remove it from those benchmarks. They updated them to use multiple cores and we don’t have time to keep the lucky implementation updated and switch it to multi core. So right now it’s way way under simply because it is using only 1 core and the others aren’t. @jwoertink just did some benchmarks against rails in the gitter room and it does many times for requests.

**Comment by paulcsmith** [comment] 2020-03-03 23:06
Wow I had no idea so many people used that benchmark. Maybe we just need to bite the bullet and update it :)

**Comment by jwoertink** [comment] 2020-03-03 23:23
There's quite a few things we could do. @paulcsmith let's chat more on that. @Sija if you have any ideas on things you see that could be easy wins, let us know!

**Comment by Sija** [comment] 2020-03-03 23:28
@jwoertink Sure, will do! I'm sure that Lucky will 🚀 into some sensible position once we level-up the playing field :)

**Comment by paulcsmith** [comment] 2020-03-03 23:50
Hopefully this will help. For awhile Lucky was way out of date, but looks it is mostly up-to-date so hopefully this will be simple https://github.com/the-benchmarker/web-frameworks/pull/2329

**Comment by waghanza** [comment] 2020-03-04 08:44
@paulcsmith feel free tune the implementation (the only requirements are the routes and to have a **production-ready** implementation) ❤️ 

DISCLAIMER : I have a bot for `go`, `ruby` ... that helps to have updated version, but not for any `crystal` tools (I'll try to add this feature when I can add this to my roadmap)

PS : I an the maintainer of the above benchmark

**Comment by wout** [comment] 2020-03-04 10:01
@paulcsmith 
> Wow I had no idea so many people used that benchmark. Maybe we just need to bite the bullet and update it :)

When selling a Lucky project to a client, we need proof to justify the investment. There already are a lot of compelling reasons, but numbers definitely add some important weight.

**Comment by paulcsmith** [comment] 2020-03-04 15:39
@waghanza Thank you! It appears what I did in that PR did not work with multi-core. I know Jeremy has a shard for this so I'm going to try that because I think I did something wrong. I've always used single core servers so never done a multi-core setup before :)

@wout you have a great point. I'll try to get this up to where it should be. I also want to publish some more realistic benchmarks in a blog post on or before 1.0. Stuff with more db calls, rendering lots of HTML, rendering complex JSON, etc.

**Comment by paulcsmith** [comment] 2020-03-04 16:21
Another try: https://github.com/the-benchmarker/web-frameworks/pull/2331

**Comment by wontruefree** [comment] 2020-03-04 16:50
so these benchmarks do not use any DB queries.  That seems crazy because most web application do DB queries and the complexity and abilities of an ORM API seems like something worth benchmarking.

**Comment by paulcsmith** [comment] 2020-03-04 16:55
@wontruefree Yeah this is why I didn't invest much time into them, but if people are using them to make decisions I wanna make sure it is showing good numbers :P

We'd like to do some benchmarking with realistic examples when closer to 1.0 but right now we want to focus on getting the framework polished and hope people can trust us/run their own benchmarks to see it is quite fast :D

**Comment by wout** [comment] 2020-03-04 18:21
@wontruefree Ideally we should have both. Benchmarks without DB queries show the speed of the framework itself, which is good for comparison. Here is a good example of multiple scenarios:

### Plain text
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=plaintext&l=zdk54v-f&c=6&d=9&o=e

### JSON Serialization
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=json&l=zdk54v-f&c=6&d=9&o=e

### Single query
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=db&l=zdk54v-f&c=6&d=9&o=e

### Multiple queries
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=query&l=zdk54v-f&c=6&d=9&o=e

**Comment by paulcsmith** [comment] 2020-03-05 19:42
Gonna go ahead and close this. The next release of benchmarks should have Lucky up in the top 20s or so. We'll add more benchmarks in the future though!

**Closed by paulcsmith** 2020-03-05 19:42 UTC

**Comment by konung** [comment] 2020-09-04 05:12
@paulcsmith FYI
I was just reading this thread and  checked the last result from August 2020 -  https://github.com/the-benchmarker/web-frameworks and despite your pull-request ⬆️ , lucky is in the very last place :( 
My guess is something is wrong with benchmark or how it's run, and not Lucky :)

**Comment by paulcsmith** [comment] 2020-09-04 14:49
@konung Yes something is wrong with the benchmarker or maybe with how it is set up on their end. Unfortunately the benchmarker changes a lot and this makes it very hard to keep everything up to date and working. I believe they are doing a new run soon that will fix it, but if not we'll have to take another look

**Comment by jwoertink** [comment] 2020-09-04 15:29
@konung I actually wanted it in last place intentionally 😂  Yes, as Paul mentioned, there's an issue with how the benchmark is setup, but I thought, if we show up in like "80th place", it looks like we're slow; however, in last place it clearly looks like a mistake. Plus, it gives us more visibility 🤫  😉 I think the next benchmark update will end up pushing us up near the top anyway.

Really, if you look at what it's benchmarking, it's essentially just routing and returning "hello world" which isn't really helpful in a real-world sense. It doesn't take into account how the framework's ORM handles SQL, or rending HTML which are really the two biggest parts to a framework.

If you happen to talk to anyone that mentions "oh, lucky is slow, look at this benchmark", just tell them it's a feature, not a bug 😜  KIDDING! Just let people know we're aware, and they should still give Lucky a shot. 😄

**Comment by konung** [comment] 2020-09-04 16:10
Yep , I looked at the code and saw it’s mostly the router that’s getting tested :(

Tech empower benchmark is a bit more advanced in that sense, and also distinguishes between full stack frameworks like lucky, rails  or Phoenix  VS micro frameworks or routers like Toro, which lets user compare apples to apples
