### ISSUE TITLE
A Call for Unity: Class Naming

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#434] opened 2018-04-25 20:07 UTC
The Lucky framework exceeds Ruby on Rails (RoR) in breaking up everything concerning a data class into little files. Generally this is done for good reasons. Keeping all of your actions for a data class in one file, as RoR generally does, makes generating new actions impossible after the user has first edited an action file. So, Lucky splits them. Unlike RoR, Lucky splits model objects into three classes. As generated and using the stated conventions for the Lucky framework, a <code>User</code> model with a <code>Users::Create</code> action would have a <code>UsersQuery</code> query class, a <code>UsersCreateForm</code> and a <code>UsersCreatePage</code>.

This gets in the way if one wishes to create standard templates for things. A typical action making use of all of the necessary objects (with the rest of the necessary code hoisted into our <code>do_create()</code> method of BrowserAction), might look like this:

```crystal
class Manufacturers::Create < BrowserAction
 action do
   do_create(ManufacturersCreateForm, ManufacturersNewPage)
 end
end
```

However, we could easily do away with the excessive number of unique class names in this action, using a little renaming. Consider that we could rename the forms and pages to Manufacturers::CreateForm and Manufacturers::NewPage. The action then looks like this:

```crystal
class Manufacturers::Create < BrowserAction
 action do
   do_create(CreateForm, NewPage)
 end
end
```

The Crystal and Lucky solution to this issue so far is to use macros, so that the un-orthagonal class names are dealt with by string transformation rather than the type system as above. The problem with this is that macros make it more difficult to understand what is actually happening in your code, and emit more cryptic debugging output than methods and functions when an error is triggered within them. A downside of macros in addition is that they appear exactly as functions or methods to the naive programmer, however they take textual parameters rather than variable parameters. This propagates through a program: if you want to pass a parameterized argument to a macro rather than a textual constant, the caller must itself be a macro.

Using the type system to disambiguate these objects is a cleaner, less verbose, and more easy to understand solution.

Let's consider models and queries. A <code>User</code> model has a User<strong>s</strong>Query class for its queries. This follows a RoR tradition to pluralize everything to do with a data object other than the object name itself. I submit that this should be called User::Query. Further discarding the pluralization we would have a User::Create action, a User::CreateForm, and a User::CreatePage. And action URLs like /users/new would become /user/new .

The existing style choices reflect a perception that models define a singular record and all other activities deal with plural records. They are not strictly necessary to either the Lucky or RoR framework, one can rather laboriously rename directories and filenames and edit class names. They are entirely stylistic and it does not particularly contribute to programmer or user understanding that these things are pluralized. Indeed, it is one more convention to be learned.

Lucky can, and should, depart from Rails conventions where they can be improved. Thus, I propose that the programming convention and default grenerated code place everything that has to do with a User model under User::, giving us object names like User, User::Query, User::New (action), User::NewPage, User::CreateForm.

For now, I'll simply manually edit my code so that it operates this way. Please don't change the framework in a way that would break this.

**Comment by paulcsmith** [comment] 2018-04-25 20:25
Thanks again @BrucePerens for all the thoughts. I debated this myself when trying to figure out the conventions. I'll break this down into a few sections:


## A small correction

* Queries and forms are generated as singular: `UserQuery`, `UserForm`. I don't think that affects the points in your article, but I thought I'd add that in case someone comes here and is confused.

## Goal I had/have when thinking about the conventions in Lucky

* As few conditionals as possible. I don't want to have to remember when to pluralize/singularize stuff
* Easy to figure out without knowing the framework conventions
* Things should be concise. Don't want to have to have to module/class, e.g.:
```crystal
module User
  class Create
  end
end
```
* I don't want things to be too deeply namespaced: `Web::Actions::User::Create`. I think that is not helpful and is hard to remember.
* Should not require files to be required in a certain order if possible.

## Some concerns

* This *could* introduce issues like this: https://play.crystal-lang.org/#/r/3y3u, but since models are required *first* it should *usually* not be an issue. It might be a problem though if the namespace you choose doesn't have a model, but *does* have another class you load later. I think this is rare though (I can't even think of a use-case), but it is something to be aware of.
* Breaking what people are used to regarding route names. In Phoenix/Rails and other frameworks, the route names are typically pluralized. I think `/user` might be a bit confusing when it goes to a user index. I think that resources should still be pluralized. **This can be done automatically by the framework though. Thoughts?**
* How should tables be named? Also `singular` to avoid confusion? I think that a pluralized table name makes the most sense conceptually, but that may be confusing. Maybe it can be avoided by making it so users don't really deal with it, e.g.

```crystal
class User < BaseModel
  # Infers table name
  table do
  end
end

# in migrations
# creates a correctly named table
create_table_for User do
end
```

## Overall thoughts

I think this is a good idea. I want to try it out a bit on a project to see how it feels, but I think this is a positive direction in almost every way.

Any other thoughts/concerns/ideas that people have?

**Comment by paulcsmith** [comment] 2018-04-25 20:36
I also wonder if/how confusing it will be to newcomers if they see an action like this:

```crystal
class User::Index < BrowserAction
  action do
    # What is Query?
    render IndexPage, users: Query.new
  end
end
```

I *think* this is something that would be fairly simple to pick up as it is something in Crystal, not Lucky. I want to document the concern just in case someone thinks this would be confusing

**Comment by BrucePerens** [comment] 2018-04-25 20:45
Let's consider how this action would be generalized. In my BrowserAction#do_index, I would take the class objects for IndexPage and Query as arguments. I would not pass `users:` but a class-independent name like `records:`

This is important because I find that any particular action is doing almost exactly the same thing across all classes. All Index actions get do something like Query.new.all and pass that to a page to be rendered. All Show actions do something like Query.id(n).limit(1).first?, check it for nil, and pass it to a page to be rendered. Etc. I don't write these things individually rather than across all classes, and don't  think anyone should. Indeed, it would be easy to generate code to call by default a framework function in BrowserAction rather than punt and generate "render something here".

**Comment by paulcsmith** [comment] 2018-04-25 20:48
@BrucePerens can you include a more in-depth example so I can see what `do_index` looks like, what the page looks like, etc.? I'm having a hard time visualizing what you're doing

**Comment by BrucePerens** [comment] 2018-04-25 20:49
```
def do_create(form, new_page)
    # params will have the form params sent from the HTML form
    form.create(params) do |form, object|
      if object # if the user was saved
        flash.success = "Your information was saved."
        redirect to: Home::Index
      else
        flash.danger = "Failed: #{form.error_messages}"
        render new_page, form: form
      end
    end
  end
```

**Comment by BrucePerens** [comment] 2018-04-25 20:50
Called as in the original posting:
```
class Manufacturers::Create &lt; BrowserAction
 action do
   do_create(CreateForm, NewPage)
 end
end
```

**Comment by paulcsmith** [comment] 2018-04-25 20:53
Oh I see. We've talked about extracting some stuff like that, but the problem is that it breaks down fairly quickly as pages get more complex. For example the Manufacturers page might need some extra variables,  or you might want a different flash message. People might then start putting conditional logic in `do_create` which would quickly grow into a God method. I think this approach could definitely work, but I'm not sure it should be *the* way to do it in Lucky. 

But this may be worth opening a separate issue since I don't think this affects how things should be namespaced. What do you think?

**Comment by BrucePerens** [comment] 2018-04-25 20:55
The point is that the way that things are namespaced should be easily usable by a function like the type I've shown. Actually adding such functions to the framework can be the topic of another discussion.

**Comment by paulcsmith** [comment] 2018-04-25 20:56
Ok, I *think* see what you are saying. Does what you described not work right now? I'm guessing it fails because of the call to `render` is a macro. If that's the case then that will be fixed when I change that to a regular method

**Comment by BrucePerens** [comment] 2018-04-25 20:57
I think it actually works with render right now. Lucky, I guess.

**Comment by BrucePerens** [comment] 2018-04-25 21:01
By the way, you can still generate the full class names rather than count on the type system. Just as long as it's easy for the user to make use of their own template without them. So, you might generate:
```
class Manufacturers::Create < BrowserAction
 action do
   do_create(Manufacturers::CreateForm, Manufacturers::NewPage)
 end
end
```
That way, the user knows what NewPage is. But I can come along and replace it with this:
```
class Manufacturers::Create < BrowserAction
 action do
   do_create(CreateForm, NewPage)
 end
end
```

**Comment by paulcsmith** [comment] 2018-04-25 21:09
That is a good idea. Leave it up to them to simplify if that's what they/they're team prefer 👍

**Comment by paulcsmith** [comment] 2018-04-26 16:04
I think this is the approach I'll take. It's mostly what @BrucePerens propose with a few changes & additions.

* `User` - the model
* `User::Show/Create/etc`. - the RESTful actions
  * Note: the routes are still pluralized: - `User::Index` -> '/users'
* `User::Form`
* `User::Collection` - Note `Query` -> `Collection`. This makes more sense since you can also issue updates and eventually deletes, e.g. `User::Collection.new.admin(false).delete_all`. These would go in `src/collections` instead of `src/queries`
* `User::NewPage`
* `User::Row` - for components
* Table names are still pluralized

So the only plurals are for RESTful path names and table names, both of which will be inferred:

* For actions it is inferred when using the `action` macro
* For tables it will be inferred by making the `table` macro infer the table name
* For migrations `create User` will be allowed and will infer the pluralized name automatically

This way the conventions for pluralization are mostly abstracted away. You only need to know the table names are pluralized if writing custom SQL. You also need to know that paths are pluralized. I think this is a worthwhile tradeoff since the paths and tables will make a lot more sense pluralized. For the most part I think this will be much simpler to understand/remember and will also allow for shorter references as Bruce mentioned.

Thoughts?

**Comment by BrucePerens** [comment] 2018-04-26 16:50
That looks fine, thanks for working upon it. The only change I was thinking about, and I don't have a really strong opinion about this, would be to rename Collection to DB. And what is presently in ./db to ./schema .

**Comment by jwoertink** [comment] 2018-04-26 17:54
This is interesting. I'm all down for naming conventions. At first it feels weird thinking about something like `User::Index` because it's been ingrained that collections should use plural, but then again, an Index page isn't always a collection of things. Like `Dashboard::Index` or `Session::Index`. I guess the main thing is that it works for model backed resources and non-resource type things.

**Comment by paulcsmith** [comment] 2018-04-26 18:08
Great question. My first thought would be to make namespaces whatever you want *if* they are not resources in the REST sense. So `Admin`, `Api`, etc. are fine. If it is a resource then it would probably be singular. For example a blog post that has comments: `Post::Comment::Create` and `Post::Comment::Index`. Of if you have an admin namespace: `Admin::Post::Comment::Create` which would generate a route of `admin/posts/:post_id/comments`

What do you think of that?

**Comment by jwoertink** [comment] 2018-04-26 18:13
That makes sense. I dig it.

**Comment by paulcsmith** [comment] 2018-04-26 18:16
One thing to note though is that this will not allow you do use the shorthand `Form` and `Collection` since it will be under a namespace. An example will make more sense:

```crystal
class Post < BaseModel
  # set up the model
end

class Admin::Post < BrowserAction
  action do
    # Won't work because this is nested in Admin::Post, not Post
    # Must use Post::Form
    Form.create(params) do |form, post|
      # do stuff with the form
    end
  end
end
```

This might be confusing for new Crystal users so it may be best to always use the fully-qualified names in guides/docs, e.g. `Post::Form` and never just `Form`.

**Comment by paulcsmith** [comment] 2018-04-26 18:29
Bad news, this actually will not work without adding `::`

* Does not work: https://play.crystal-lang.org/#/r/3ydz
* Works when adding `::` so the compiler knows to look at the top-level `Post`https://play.crystal-lang.org/#/r/3ye5

I think this puts a major wrench in the idea of namespacing actions and pages in the singular, as it will cause a bunch of issues like this that tend to be hard to figure out and debug, especially for people unfamiliar with the way Crystal/Ruby looks up methods. It is not clear from the error message in https://play.crystal-lang.org/#/r/3ydz what the problem is.

**Comment by jwoertink** [comment] 2018-04-26 18:43
Yeah, that's true. You'd have to set it up like https://play.crystal-lang.org/#/r/3yek for it to work, and that starts to make things a little ugly having stuff like `::Post.new` all over

**Comment by paulcsmith** [comment] 2018-04-26 18:45
Agreed. I think that's far more verbose and much less pleasant to read/write

**Comment by BrucePerens** [comment] 2018-04-26 21:12
Would it be possible to use a class for namespaces, and make use of method_missing() to handle this?

**Comment by jwoertink** [comment] 2018-04-26 21:15
I'm not sure how the method_missing macro works in crystal, but I don't think that would work. The issue with the example above would be that crystal assumes you're calling a module instead of a class, or possibly that it's the wrong class. I guess if you caught it with method missing, then you'd have to assume that the top level `::Whatever` would have the method you were looking for. My guess is that would lead to witch hunts in the case of a typo or something.

**Comment by BrucePerens** [comment] 2018-04-26 21:43
Hm. Maybe using modules for routing namespaces isn't that great an idea. They've only not broken things up until now because their names didn't collide with anything else. We really have to maintain that constraint, don't we?

**Comment by paulcsmith** [comment] 2018-04-26 22:02
I’m not sure that modules for namespacing routes is the problem. It makes sense to me but I am biased of course

I’m also not sure what else would be used. If you have a Posts::New for public access and a Posts::New for admins only, I think you’d have to use a module for the namespace so they don’t conflict

**Comment by BrucePerens** [comment] 2018-04-26 22:04
Admin_Posts::Create instead of Admin::Posts::Create . It gets its own dumb namespace and you are back to using fully disambiguated names for what you call, but it doesn't break the common case.

**Comment by paulcsmith** [comment] 2018-04-26 22:04
I think the best bet given the technical constraints is to keep everything as-is with the exception of forms and queries/collections which would be namespaced under the model class, e.g. User::Form

**Comment by paulcsmith** [comment] 2018-04-26 22:10
Ah I see. The problem I see with that approach is it makes folder naming difficult. Instead of having all your admin stuff in an /admin folder you’d have an /admin_posts, /admin_users, etc. either that or you’d break convention and put it under /admin but that seems like an odd special case. It would also break the inference of routes. You’d have to specify all your routes manually with that approach (unless you’re ok with /admin/posts). It’d also not clear how that would work with nested resources: AdminPostsComments::create? Maybe that’d work but it doesn’t quite feel right

**Comment by raydf** [comment] 2018-04-27 03:04
This works for namespacing with modules:
https://play.crystal-lang.org/#/r/3yhs
I don't see the problem with namespacing with ::Post.new.title or using the module for grouping as:
```
module Admin::Post.
```

**Comment by BrucePerens** [comment] 2018-04-27 03:49
Well, given the choice of using namespaces or having templating be easier, I will probably just not use namespaces and keep my actions singular.

**Comment by paulcsmith** [comment] 2018-11-06 03:13
Going to go ahead and close for now. We're looking at a few things for improving structure and namespaces in the future #642

**Closed by paulcsmith** 2018-11-06 03:13 UTC
Labels: discussion
