### ISSUE TITLE
no overload matches 'Lucky::ProtectFromForgery.get_token' with type (HTTP::Server::Context | Nil)

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1526] opened 2021-06-09 20:49 UTC
Booted a new project against master branch, and got this error:

```
web          |
web          |  23 | content: ProtectFromForgery.get_token(context)
web          |                                   ^--------
web          | Error: no overload matches 'Lucky::ProtectFromForgery.get_token' with type (HTTP::Server::Context | Nil)
web          |
web          | Overloads are:
web          |  - Lucky::ProtectFromForgery.get_token(context : HTTP::Server::Context)
web          | Couldn't find overloads for these types:
web          |  - Lucky::ProtectFromForgery.get_token(context : Nil)
web          |
web          | ---
```

Related:  https://github.com/luckyframework/lucky/pull/1488

**Comment by matthewmcgarvey** [comment] 2021-06-09 21:21
Might be a duplicate of https://github.com/luckyframework/lucky_cli/issues/639

**Closed** 2021-06-16 01:54 UTC
Labels: bug
