### ISSUE TITLE
SaveOperation fails claiming unrequired, but present, column is required

### ISSUE THREAD

**Issue by InstanceOfMichael** [luckyframework/lucky#1004] opened 2020-02-02 18:26 UTC
```
class SignUpUser < User::SaveOperation
  param_key :user
  include PasswordValidations

  permit_columns email
  permit_columns handle
  permit_columns description
  attribute password : String
  attribute password_confirmation : String

  before_save do
    # set default value for description,
    # because description is NOT NULL and not in the signup form
    # user will optionally add a value later
    self.description.value = ""
    validate_size_of handle, min: 3, max: 24
    validate_size_of description, min: 0, max: 256
    validate_uniqueness_of email, query: UserQuery.new.email.lower
    validate_uniqueness_of handle, query: UserQuery.new.handle.lower
    validate_confirmation_of password, with: password_confirmation
    Authentic.copy_and_encrypt password, to: encrypted_password
  end
end
```
outputs:
```
web    | POST /sign_ups
web    |  ▸ Handled by SignUps::Create
web    |  ▸ Ran verify_accepted_format
web    |  ▸ Ran protect_from_forgery
web    |  ▸ Ran test_backdoor
web    |  ▸ Ran redirect_signed_in_users
web    |  ▸ Failed to save SignUpUser. Validation errors description is requiredb
web    |  ▸ Rendered SignUps::NewPage
web    |  ▸ Sent 200 (43.67ms)
```

**Comment by jwoertink** [comment] 2020-02-02 18:44
This is essentially the same as https://github.com/luckyframework/avram/issues/294 

The validation calls `.blank?` which an empty string would be considered blank. This is like passing nothing through the form. For a temp hack until this is fixed, you might be able to call 

`description..reset_errors` in that before_save to get around it. Looks like we need to rethink validations.

Thanks for reporting these issues! These are the kinds of things we need to see with people using Lucky so we can really think about how stuff should be structured. If you have any ideas on that, I'd love to hear those as well.

**Comment by paulcsmith** [comment] 2020-03-01 17:16
Just noticed this! Sorry for the late response. This is the expected behavior for an empty string. We treat `""` as blank since we can't differentiate between params wanting a field to `""` or `nil`. The other reason is that it introduces multiple ways for something to be "not filled in". It could be `nil` or `""` which can get confusing. This also prevents errors where something should *really* have value. For example, if you have a required email, you wouldn't want `""` to be email address. This is also the way Rails works and Phoenix strips empty "". I hope that makes sense

The way to get around this is to make the column allow null and instead leave the description null for new users. I hope that helps! I'm going to close this, but feel free to comment if you need more help on this!

**Closed** 2020-03-01 17:16 UTC

**Comment by InstanceOfMichael** [comment] 2020-03-01 17:31
But I don't want the column to be billable.

**Comment by paulcsmith** [comment] 2020-03-01 17:40
@InstanceOfMichael But it does allow `""` right? If so I'm not sure what you get out of making it non-nullable but allowing an empty string. Could you share what the use-case is for that that making it nullable doesn't solve?

**Comment by InstanceOfMichael** [comment] 2020-03-01 17:47
I don't have to null check it all throughout my code.

**Comment by paulcsmith** [comment] 2020-03-01 17:53
@InstanceOfMichael But in a way you do because you may have an "empty" value:

```crystal
h3 "Description"
text user.description # This will show an empty description
```

So in this case having to check would show a compile time-error so you can handle it differently: `user.description || "No description"`.

Now another solution would be to make it nullable and then handle it in an instance method on the User

```
class User
  # table, etc.

  def description : String
    super || ""
  end
end
```

This way you have a default empty stringm, but your database schema is more correct in storing data.

I would consider an option to allow `""` if someone presents a use-case, but so far I think the nil check has been super valuable in catching bugs. Since `""` in most UIs or other code typically means there is nothing there to work with. But if you really need it and have a use-case for how the nil chek is not helpful could you post it so we can give it a look? The overriding the `decription` method in the model should do the trick in the meantime
