### ISSUE TITLE
GET /todos , works fine, but calling GET /todos/ (notice the slash / at the end), gives LuckyRecord error

### ISSUE THREAD

**Issue by thegreyfellow** [luckyframework/lucky#392] opened 2018-02-10 16:35 UTC
I noticed something when I call `GET /todos` it works fine, but when I call `GET /todos/`(notice the slash `/` at the end). I get a `LuckyRecord` error.

Backtrace:
```
ERROR: cast from LuckyRecord::Type::FailedCast to LuckyRecord::Type::SuccessfulCast(T) failed, at /Users/idmoussiyoussef/Projects/crystal/lucky_todo/lib/lucky_record/src/lucky_record/type.cr:15:5:15 (TypeCastError)
  from lib/lucky_record/src/lucky_record/type.cr:0:5 in 'parse!'
  from lib/lucky_record/src/lucky_record/type.cr:23:5 in 'to_db!'
  from lib/lucky_record/src/lucky_record/criteria.cr:20:16 in 'is'
  from src/models/todo.cr:2:3 in 'id'
  from lib/lucky_record/src/lucky_record/queryable.cr:81:5 in 'find'
  from src/actions/todos/show.cr:2:3 in 'call'
  from lib/lucky/src/lucky/renderable.cr:37:16 in 'perform_action'
  from lib/lucky/src/lucky/route_handler.cr:10:7 in 'call'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/lucky/src/lucky/error_handler.cr:14:5 in 'call'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/lucky/src/lucky/flash.cr:18:9 in 'call'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/lucky/src/lucky/session_handler.cr:7:8 in 'call'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/lucky/src/lucky/log_handler.cr:15:5 in 'call'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/lucky/src/lucky/http_method_override_handler.cr:11:5 in 'call'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server/request_processor.cr:16:3 in 'process'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server.cr:190:5 in 'handle_client'
  from ~procProc(Nil)@/usr/local/Cellar/crystal-lang/0.24.1_2/src/http/server.cr:163
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/fiber.cr:255:3 in 'run'
  from ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@/usr/local/Cellar/crystal-lang/0.24.1_2/src/fiber.cr:29

```
Environnement:
Crystal: 0.24.1
Lucky: 0.8.0
Lucky Record: master

Test app:
[thegreyfellow/lucky_todo]( https://github.com/thegreyfellow/lucky_todo)

**Comment by paulcsmith** [comment] 2018-02-10 16:54
Thanks so much for posting! The problem is that it is trying to match the Todos#Show route but it has an empty string as the id. So I likely need to remove the trailing slash in the router so it doesn’t think it’s another path part

**Comment by thegreyfellow** [comment] 2018-02-10 17:28
Awesome 🙏

**Comment by Jcambass** [comment] 2018-03-30 13:14
I just had a look into the code, but there are some questions that popped up:

#### Double Slashes
Should the router be able to handle routes like `/management//users`
I know that rails is able to ignore double slashes that may occur. See also this [thread on SO](https://stackoverflow.com/a/20524044/6001928)

#### URL parameters
Should the router accept "router parameters" like :id in the query string rather than in the route itself?
Route definition `router.add("get", "/management/users/:id", :show)`
Params in the route `/management/users/some_id`
Params in query string `/management/users?id=some_id`

Supporting the second scenario (params in query string) also complicates the handling of nested route params.

#### My two cents

The pragmatic solution is to just treat routes with trailing slashes the same way as those without.
This solution has the side effect of not warning the user if they meant to call a show route `/management/users/:id` but just called `/management/users/`.  This problem grows if we want to support multiple trailing slashes.

**Comment by paulcsmith** [comment] 2018-05-26 02:39
Closing this as @Jcambass fixed it in https://github.com/luckyframework/lucky_router/pull/5

Thank you!

**Closed by paulcsmith** 2018-05-26 02:39 UTC
