### ISSUE TITLE
Flash messages stay around with Turbolinks enabled

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1093] opened 2020-04-10 19:24 UTC
Disabling Turbolinks fixes the issue. Maybe flash messages are not cleared when performing XHR requests? Maybe related to #277?

**Comment by confact** [comment] 2020-04-18 08:44
Notice this as well, if I click on links it persists. But if I do a real refresh (cmd+r / F5) it disappears. 

do @jwoertink or @paulcsmith know what the problem is here?

**Comment by jwoertink** [comment] 2020-04-18 17:01
Nope. No clue 🤷‍♂️

**Comment by paulcsmith** [comment] 2020-04-18 17:26
I need to look into it. But haven’t spent time on it yet. I need to get Dexter out so it removes all those warnings. Then I can look at this and others. 

May have something to do with https://github.com/luckyframework/lucky/issues/1064

Since flashes are stored in the session

**Comment by jwoertink** [comment] 2020-05-06 17:26
Now that #1133 is merged, we should see if this is fixed.

**Comment by confact** [comment] 2020-05-09 11:47
This seems to work now in Lucky 0.21.1

Do a last check and then I think you can close this :)

**Comment by jwoertink** [comment] 2020-05-09 17:50
Yeah, this is looking good to me. If anyone runs in to this issue, we can reopen. Thanks @skojin !

**Closed by jwoertink** 2020-05-09 17:50 UTC
Labels: bug

**Comment by wout** [comment] 2020-05-30 07:29
This is still not fixed for me. I'm using the latest master with the fixes for #1064 and flash messages still stick around when Turbolinks is enabled. It's easy to reproduce by adding the following action:

```cr
class SomeAction::Index < BrowserAction
  route do
    flash.failure = "I'm stubborn"
    redirect to: AnotherAction::Index
  end
end
```

If Turbolinks is enabled, the message stays there forever until a hard refresh, upon which it's shown one more time, and the next click on a link it's gone. With Turbolinks disabled, it works as expected.

**Comment by wout** [comment] 2020-05-30 09:32
I can confirm this works as expected.
