### ISSUE TITLE
Is it possible to provide a helpful error message when rendering fails?

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky#661] opened 2018-12-18 16:39 UTC
Lucky is so helpful, and I love working with a framework that has a bit of extra thought put in to help me recover from the mistakes I make. Perhaps this mistake is a place that a simple helper message can be emitted, perhaps not.

Here is the somewhat opaque error I got:

```text
in lib/lucky/src/lucky/renderable.cr:85: no overload matches 'Home::Index#handle_response' with type (Lucky::TextResponse | Nil)
Overloads are:
 - Lucky::Renderable#handle_response(response : Lucky::Response)
```

The reason this is opaque is that none of my code is present anywhere in the trace...as a developer I have nothing to go on. A git stash / bisect type workflow eventually led me to this code:

```crystal
class SessionForm < LuckyRecord::VirtualForm
  # drastically simplified code
  def submit
    validate_required email
    validate_required password

    unless valid?
      yield self, nil
      return
    end

    # more validations...
  end
end

class Session::Create < BrowserAction
  post "/session/new" do
    SessionForm.new(params).submit do |form, authenticated_user|
      if authenticated_user
        redirect to: Home::Index
      else
        render NewPage, form: form
      end
    end
  end
end
```

The problem is that my action was returning nil, which isn't supported. The reason it was returning nil is a simple mistake in the form:

```crystal
    unless valid?
      yield self, nil
      return
    end
```
Should instead be:
```crystal
    unless valid?
      return yield self, nil
    end
```

Could this have a better compile-time message? If not, what about a nil-accepting overload for #handle_response should be able to provide a better run-time failure message?

**Comment by paulcsmith** [comment] 2018-12-18 17:03
Thank you for opening this! It is definitely possible and used to be implemented, but there was in issue in Crystal that caused the error to show the wrong class name. There is an issue here for re-adding the error case: https://github.com/luckyframework/lucky/issues/460

I'll close this in favor of that one, but I'll prioritize adding that back in and seeing if the issue is fixed in Crystal!

I'm glad `handle_response` at least caught the error, but totally agree it could be more helpful about telling you what is wrong!

**Closed by paulcsmith** 2018-12-18 17:03 UTC
