### ISSUE TITLE
Routes that differ in file extension only get confused

### ISSUE THREAD

**Issue by wezm** [luckyframework/lucky#928] opened 2019-10-03 01:27 UTC
I defined two actions, which somewhat accidentally ended up with a different name for the leading param (`:slug` vs. `:category`):

```crystal
class RssFeed::Show < BrowserAction
  include Auth::AllowGuests

  get "/:slug/feed.rss" do
    plain_text "Render something in RssFeed::Show #{slug}"
  end
end
```

```crystal
class JsonFeed::Show < BrowserAction
  include Auth::AllowGuests

  get "/:category/feed.json" do
    plain_text "Render something in JsonFeed::Show"
  end
end
```

Requesting `/community/feed.rss` results in the error:

```
web    | GET /community/feed.rss
web    |  ▸ Handled by RssFeed::Show
web    |  ▸ Ran protect_from_forgery
web    |  ▸ Ran test_backdoor
web    |  ▸ Unhandled error Missing parameter: slug (Lucky::Exceptions::MissingParam)
web    |   from lib/lucky/src/lucky/params.cr:37:5 in 'get'
web    |   from src/actions/rss_feed/show.cr:4:3 in 'slug'
web    |   from src/actions/rss_feed/show.cr:5:16 in 'call'
```

Inspecting `route_params` it looks like this: `{"category" => "community"}`.

If I change the name of the param in the second action then the `route_param` changes accordingly. So it appears the `route_params` are being set according to the second action, even though the request is routed to the first action.

This may be related to/have a bearing on:

* https://github.com/luckyframework/lucky/issues/771
* https://github.com/luckyframework/lucky/pull/778

**Lucky Version:** 0.17.0

**Comment by wezm** [comment] 2019-10-03 02:36
I've written a failing test here: https://github.com/wezm/lucky/commit/9b8ac5eca62bed21d40c1f7dfd6a1cf7a89c1289

**Comment by paulcsmith** [comment] 2019-10-03 14:24
@wezm Thanks for opening and for writing a failing test case :D

Could you open a draft PR with the failing test case? That makes it a tad bit easier to see the error the that happens and keep track of where things are at.

In the meantime you could try prefixing `/categories/:category/feed.json` and `slugs/:slug/feed.rss` as a workaround. I *think* that'll work!

**Comment by wezm** [comment] 2019-10-03 23:48
> Could you open a draft PR with the failing test case? That makes it a tad bit easier to see the error the that happens and keep track of where things are at.

Sure, have done that.

> In the meantime you could try prefixing /categories/:category/feed.json and slugs/:slug/feed.rss as a workaround.

Thanks, I ended up making them both use the same prefix (`/:slug/feed.rss` and `/:slug/feed.json`), which works. That they were using a different prefix was mostly an accident.

**Comment by matthewmcgarvey** [comment] 2020-09-15 22:01
This issue is caused by https://github.com/luckyframework/lucky_router/issues/1

**Comment by paulcsmith** [comment] 2020-10-22 20:01
Will close this since it is tracked in LuckyRouter. Thanks for opening this @wezm

**Closed by paulcsmith** 2020-10-22 20:01 UTC
