### ISSUE TITLE
prefix id params bug

### ISSUE THREAD

**Issue by skojin** [luckyframework/lucky#1264] opened 2020-09-20 13:36 UTC
Related to https://github.com/luckyframework/lucky/issues/659
lucky version: ~> 0.24.0

```
# lucky gen.action.browser Tests::Show
class Tests::Show < BrowserAction
  route do
    plain_text "Render something in Tests::Show #{test_id}"
  end
end
```
Visit http://127.0.0.1:3001/tests/1 render successfully "Render something in Tests::Show 1"

add new action to same resource but use different :id param name
```
class Tests::Custom < BrowserAction
  get "/tests/:id/custom" do
    plain_text "Render something in Tests::Custom #{id}"
  end
end
```
Visit http://127.0.0.1:3001/tests/2/custom render successfully "Render something in Tests::Custom 2"

But Visit http://127.0.0.1:3001/tests/1 give Error
```
Error 400 at GET /tests/1
Missing parameter: 'test_id'
```

<img width="928" alt="Screen Shot 2020-09-20 at 16 32 11" src="https://user-images.githubusercontent.com/8044/93712495-e2df3d00-fb5e-11ea-95ea-0f16e5bab526.png">

```
web.1    | GET /tests/1
web.1    |  ▸ Handled by Tests::Show
web.1    |  ▸  Lucky::MissingParamError 
web.1    | 
web.1    |      Missing parameter: 'test_id'
web.1    | 
web.1    |     Backtrace 
web.1    | 
web.1    |      lib/lucky/src/lucky/params.cr:136:22 in 'get_raw'
web.1    |      lib/lucky/src/lucky/params.cr:110:5 in 'get'
web.1    |      src/actions/tests/show.cr:2:3 in 'test_id'
web.1    |      src/actions/tests/show.cr:3:51 in 'call'
web.1    |      lib/lucky/src/lucky/renderable.cr:123:16 in 'perform_action'
web.1    |      lib/lucky/src/lucky/route_handler.cr:10:7 in 'call'
web.1    |      ../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
web.1    |      lib/lucky/src/lucky/remote_ip_handler.cr:15:5 in 'call'
web.1    |      ../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
web.1    |      lib/lucky/src/lucky/error_handler.cr:14:5 in 'call'
web.1    |      ../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
web.1    |      lib/lucky/src/lucky/log_handler.cr:28:5 in 'call'
web.1    |      ../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
web.1    |      lib/lucky/src/lucky/http_method_override_handler.cr:11:5 in 'call'
web.1    |      ../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
web.1    |      lib/lucky/src/lucky/force_ssl_handler.cr:37:7 in 'call'
web.1    |      ../../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
web.1    |      ../../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
web.1    |      ../../usr/share/crystal/src/http/server.cr:468:13 in '->'
web.1    |      ../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
web.1    |      ../../usr/share/crystal/src/fiber.cr:92:34 in '->'
web.1    |      ???
web.1    | 
web.1    |  ▸ Sent 400 Bad request (105.35ms)

```

**Comment by jwoertink** [comment] 2020-09-20 16:16
Ah, bummer. Sounds like we should take this time to remove `route` and `nested_route`. https://github.com/luckyframework/lucky/discussions/789

**Comment by matthewmcgarvey** [comment] 2020-09-20 18:26
Connected https://github.com/luckyframework/lucky_router/issues/1

**Comment by paulcsmith** [comment] 2020-09-21 15:59
I'll go ahead and close this. The issue is that the router requies it to use the same param name. The fix is to raise an error: https://github.com/luckyframework/lucky_router/issues/1 as allowing different param names there will mess up the routing (at least how Lucky router works now).

So I'd follow that issue. Sorry you ran into this!

**Closed by paulcsmith** 2020-09-21 15:59 UTC
Labels: bug
