### ISSUE TITLE
Add support for optional route params

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky#815] opened 2019-06-18 20:36 UTC
Currently the only way to have optional parameters in a route is to use query params such as:

```crystal
param param_name : Type?
```

This is ok, but not the easiest to type or the most pleasing to look at. Rails allows you to implement optional route parameters with the following format:

```
get "/blog/:post/(:revision)"
get "/tags/:tag_name(/sort/:order)
```

Where everything in parentheses is considered optional.

**Comment by paulcsmith** [comment] 2019-06-18 20:57
From Gitter https://gitter.im/luckyframework/Lobby?at=5d094ba8a8d9871b32bc330b

> Another possibility is router remains unchanged but when calling get/put/post/etc in Lucky it creates two routes under the hood that each point to the same action. And when it generates the param method (:version -> created a version instance method) it would make the optional one nilable
That may be easier and would keep the LuckyRouter super simple

This way we would not require any changes to LuckyRouter

**Comment by paulcsmith** [comment] 2019-06-18 21:02
Also here is an example of a workaround (if you don't want to use query params)

https://gist.github.com/paulcsmith/e53b0c147ffdb9ffd7fd1df0b64d49ff

**Comment by matthewmcgarvey** [comment] 2020-12-26 19:13
This is a duplicate of https://github.com/luckyframework/lucky_router/issues/15

It doesn't use parenthesis, but the equivalent in lucky is `GET /block/:post/?:revision` 🎉

**Closed by matthewmcgarvey** 2020-12-26 19:13 UTC
Labels: feature request
